# Generated by Django 2.0.1 on 2018-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryCode', models.CharField(max_length=20)),
                ('categoryName', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=1)),
                ('createdTime', models.DateTimeField()),
                ('updatedTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
    ]
