# Generated by Django 2.0.1 on 2018-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='姓名')),
                ('email', models.EmailField(db_column='email', max_length=50, verbose_name='邮箱')),
                ('telephone', models.CharField(db_column='phone', max_length=11, verbose_name='手机号')),
                ('sex', models.CharField(db_column='sex', max_length=1, verbose_name='性别')),
                ('title', models.CharField(db_column='title', max_length=100, verbose_name='主题')),
                ('content', models.CharField(db_column='content', max_length=500, verbose_name='内容')),
                ('status', models.CharField(choices=[('1', '有效'), ('0', '无效')], db_column='status', default=1, max_length=1, verbose_name='状态')),
                ('createdTime', models.DateTimeField(db_column='created_time', verbose_name='创建时间')),
                ('updatedTime', models.DateTimeField(blank=True, db_column='updated_time', null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'comments',
            },
        ),
    ]
